# numpy 

In [2]:
import numpy as np

In [2]:
n=10000000
custom_list=list(range(n))
custom_array=np.arange(n)

In [4]:
len(custom_list),len(custom_array)

(10000000, 10000000)

In [12]:
from time import time

t0=time()
custom_array=custom_array*2
print(f"Time taken by numpy array: {time()-t0} secs")

t0=time()
custom_list=[i * 2 for i in custom_list]
print(f"Time taken by list: {time()-t0} secs")

Time taken by numpy array: 0.026922225952148438 secs
Time taken by list: 0.36704468727111816 secs


In [11]:
custom_list[:10]

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36]

In [10]:
custom_array[:10]

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72])

# Creating Arrays

In [23]:
print("1-D array")
a=np.array([1,2,3,4,5])
print(a)

1-D array
[1 2 3 4 5]


In [22]:
print("2-D array")
b=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(b)

2-D array
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [21]:
print("3-D array")
c=np.array([[[1,2],[3,4]],
           [[5,6],[7,8]],
           [[1,1],[1,1]],
           [[0,0],[0,0]]])
print(c)

3-D array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[1 1]
  [1 1]]

 [[0 0]
  [0 0]]]


# Basic Specifications of array:

## arr.ndim =No of dimensions

In [8]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


## arr.shape=exact shape of matrix

In [9]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(4, 2, 2)


## arr.size=no of elements in array

## arr.dtype=Type of data within arrays

## arr.itemsize =size in bytes taken by each element

## arr.nbytes=size of total in bytes

s

In [29]:
a=np.ones((5,5))
#print(a)
b=np.zeros((3,3))
#print(b)

b[1,1]=9
#b[0,0]=9999
b[0,0]=8
a[1:4,1:4]=b
a

array([[1., 1., 1., 1., 1.],
       [1., 8., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.arange(0,3,3)

array([0])

In [3]:
help(np.asarray)

Help on built-in function asarray in module numpy:

asarray(...)
    asarray(a, dtype=None, order=None, *, like=None)
    
    Convert the input to an array.
    
    Parameters
    ----------
    a : array_like
        Input data, in any form that can be converted to an array.  This
        includes lists, lists of tuples, tuples, tuples of tuples, tuples
        of lists and ndarrays.
    dtype : data-type, optional
        By default, the data-type is inferred from the input data.
    order : {'C', 'F', 'A', 'K'}, optional
        Memory layout.  'A' and 'K' depend on the order of input array a.
        'C' row-major (C-style),
        'F' column-major (Fortran-style) memory representation.
        'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
        'K' (keep) preserve input order
        Defaults to 'K'.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``lik

In [7]:
b=np.array([[1,2,4],[6,8,10],[100,99,88]])
b[0:2]

array([[ 1,  2,  4],
       [ 6,  8, 10]])

In [8]:
b[0:2,0:2]

array([[1, 2],
       [6, 8]])

In [15]:
b[0:2]

array([[ 1,  2,  4],
       [ 6,  8, 10]])

In [14]:
b[:,2]

array([ 4, 10, 88])

In [17]:
b[::-1,:]

array([[100,  99,  88],
       [  6,   8,  10],
       [  1,   2,   4]])

In [18]:
b[:,::-1]

array([[  4,   2,   1],
       [ 10,   8,   6],
       [ 88,  99, 100]])

In [19]:
b[1,2]

10

In [24]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 1],
        [1, 1]],

       [[0, 0],
        [0, 0]]])

In [25]:
c[0]

array([[1, 2],
       [3, 4]])

In [26]:
c[0,0,1]

2

In [27]:
c[1,-1,-1]

8

## Arithmatic operations with NUMPY

            * Default operation is element wise

In [28]:
a

array([1, 2, 3, 4, 5])

In [29]:
a+10

array([11, 12, 13, 14, 15])

In [30]:
a-10

array([-9, -8, -7, -6, -5])

In [31]:
a*10

array([10, 20, 30, 40, 50])

In [32]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [33]:
a**10

array([      1,    1024,   59049, 1048576, 9765625])

In [34]:
a%10

array([1, 2, 3, 4, 5])

In [35]:
a//10

array([0, 0, 0, 0, 0])

In [36]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [37]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [39]:
a*10-6+3/4

array([ 4.75, 14.75, 24.75, 34.75, 44.75])

In [40]:
a*(10-6+3/4)

array([ 4.75,  9.5 , 14.25, 19.  , 23.75])

In [50]:
d=np.ones((10,10))
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Linear Algebra

In [48]:
a=np.ones((2,3))
b=np.full((3,2),5)
print(a)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]


array([[15., 15.],
       [15., 15.]])

In [51]:
np.matmul(b,a)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [53]:
e=np.array([[1,2,3],[4,5,6]])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.sum(a,axis=0)

array([2., 2., 2.])

In [55]:
np.min(a)

1.0

In [56]:
np.min(a,axis=0)

array([1., 1., 1.])

In [57]:
np.min(a,axis=1)            #axis=1 means ROWS

array([1., 1.])

In [58]:
np.mean(a,axis=0)       #axis=0 means COLUMNS

array([1., 1., 1.])

## Reorganizing Arrays

## arr.reshape((rows,cols))

            For reshaping the Dimenstions the no.of elements should properly utilized

In [59]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
a.size

8

In [61]:
a.reshape((2,2,2,))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [62]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
a.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
a.reshape((1,2,4))

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [66]:
a.reshape((4,))

ValueError: cannot reshape array of size 8 into shape (4,)

# arr.flatten()  and  arr.ravel()


                flatten                             |                   ravel

    return copy of original array                   | returns reference/view of orignal array
    modifying value of this                         |

### arr.flatten()

In [67]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
b.flatten()

array([5, 5, 5, 5, 5, 5])

In [69]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 1],
        [1, 1]],

       [[0, 0],
        [0, 0]]])

In [70]:
c.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 1, 1, 1, 0, 0, 0, 0])

### arr.ravel = nd to 1d

In [71]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
b.ravel()

array([5, 5, 5, 5, 5, 5])

In [73]:
c.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 1, 1, 1, 0, 0, 0, 0])

### vstack()

        It places the values in vertical position

In [77]:
a=np.array([1,2,3,4,5],dtype='int32')
b=np.array([2,3,4,5,6],dtype='float64')
a


array([1, 2, 3, 4, 5], dtype=int32)

In [78]:
b

array([2., 3., 4., 5., 6.])

In [79]:
np.vstack(a)

array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int32)

In [81]:
np.vstack([a,b])

array([[1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])

### hstack

        It places the values horizontally(side by side)

## Transpose

In [84]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 1],
        [1, 1]],

       [[0, 0],
        [0, 0]]])

In [88]:
c.shape

(4, 2, 2)

In [89]:
c.T

array([[[1, 5, 1, 0],
        [3, 7, 1, 0]],

       [[2, 6, 1, 0],
        [4, 8, 1, 0]]])

In [91]:
c.shape

(4, 2, 2)

## Load data from file

            np.genfromtxt('file_name',delimiter=',')

            delimite== if we doesn't give any delimiter symbol the default is 'space'

In [95]:
data=np.genfromtxt(r'filedata.txt',delimiter=',')
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [96]:
data=np.loadtxt('filedata.txt',delimiter=',')
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

## Boolean Indexing

In [97]:
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [101]:
data > 5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [102]:
data[data > 5]

array([ 6.,  7.,  8.,  9., 10.])

In [104]:
np.where(data>5)

(array([1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4]))

# Broadcasting

In [105]:
a=np.array([[1,2,3,4,5],[1]])
b=np.array([6,7])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.